// GENERATED by core/tools/pap2kt.py from core/pap/Lohnsteuer2026.xml (BMF, Stand 2025-10-23 12:40). Do not edit:
// test/test-search-shell.sh regenerates it and fails on any difference.
@file:Suppress("LocalVariableName", "PropertyName", "FunctionName", "ObjectPropertyName", "unused", "RedundantExplicitType", "NAME_SHADOWING")

package com.diegonmarcos.cloudsearch.core.tax

import java.math.BigDecimal
import java.math.RoundingMode

/** The BMF's Lohnsteuer2026 Programmablaufplan, statement for statement. Set the inputs, call [main], read the outputs. */
class Lohnsteuer2026 {
    var af: Int = 1
    var AJAHR: Int = 0
    var ALTER1: Int = 0
    var ALV: Int = 0
    var f: Double = 1.0
    var JFREIB: BigDecimal = BigDecimal.ZERO
    var JHINZU: BigDecimal = BigDecimal.ZERO
    var JRE4: BigDecimal = BigDecimal.ZERO
    var JRE4ENT: BigDecimal = BigDecimal.ZERO
    var JVBEZ: BigDecimal = BigDecimal.ZERO
    var KRV: Int = 0
    var KVZ: BigDecimal = BigDecimal.ZERO
    var LZZ: Int = 1
    var LZZFREIB: BigDecimal = BigDecimal.ZERO
    var LZZHINZU: BigDecimal = BigDecimal.ZERO
    var MBV: BigDecimal = BigDecimal.ZERO
    var PKPV: BigDecimal = BigDecimal.ZERO
    var PKPVAGZ: BigDecimal = BigDecimal.ZERO
    var PKV: Int = 0
    var PVA: BigDecimal = BigDecimal.ZERO
    var PVS: Int = 0
    var PVZ: Int = 0
    var R: Int = 0
    var RE4: BigDecimal = BigDecimal.ZERO
    var SONSTB: BigDecimal = BigDecimal.ZERO
    var SONSTENT: BigDecimal = BigDecimal.ZERO
    var STERBE: BigDecimal = BigDecimal.ZERO
    var STKL: Int = 1
    var VBEZ: BigDecimal = BigDecimal.ZERO
    var VBEZM: BigDecimal = BigDecimal.ZERO
    var VBEZS: BigDecimal = BigDecimal.ZERO
    var VBS: BigDecimal = BigDecimal.ZERO
    var VJAHR: Int = 0
    var ZKF: BigDecimal = BigDecimal.ZERO
    var ZMVB: Int = 0
    var BK: BigDecimal = BigDecimal.ZERO
    var BKS: BigDecimal = BigDecimal.ZERO
    var LSTLZZ: BigDecimal = BigDecimal.ZERO
    var SOLZLZZ: BigDecimal = BigDecimal.ZERO
    var SOLZS: BigDecimal = BigDecimal.ZERO
    var STS: BigDecimal = BigDecimal.ZERO
    var VFRB: BigDecimal = BigDecimal.ZERO
    var VFRBS1: BigDecimal = BigDecimal.ZERO
    var VFRBS2: BigDecimal = BigDecimal.ZERO
    var WVFRB: BigDecimal = BigDecimal.ZERO
    var WVFRBO: BigDecimal = BigDecimal.ZERO
    var WVFRBM: BigDecimal = BigDecimal.ZERO
    var ALTE: BigDecimal = BigDecimal.ZERO
    var ANP: BigDecimal = BigDecimal.ZERO
    var ANTEIL1: BigDecimal = BigDecimal.ZERO
    var AVSATZAN: BigDecimal = BigDecimal.ZERO
    var BBGKVPV: BigDecimal = BigDecimal.ZERO
    var BBGRVALV: BigDecimal = BigDecimal.ZERO
    var BMG: BigDecimal = BigDecimal.ZERO
    var DIFF: BigDecimal = BigDecimal.ZERO
    var EFA: BigDecimal = BigDecimal.ZERO
    var FVB: BigDecimal = BigDecimal.ZERO
    var FVBSO: BigDecimal = BigDecimal.ZERO
    var FVBZ: BigDecimal = BigDecimal.ZERO
    var FVBZSO: BigDecimal = BigDecimal.ZERO
    var GFB: BigDecimal = BigDecimal.ZERO
    var HBALTE: BigDecimal = BigDecimal.ZERO
    var HFVB: BigDecimal = BigDecimal.ZERO
    var HFVBZ: BigDecimal = BigDecimal.ZERO
    var HFVBZSO: BigDecimal = BigDecimal.ZERO
    var HOCH: BigDecimal = BigDecimal.ZERO
    var J: Int = 0
    var JBMG: BigDecimal = BigDecimal.ZERO
    var JLFREIB: BigDecimal = BigDecimal.ZERO
    var JLHINZU: BigDecimal = BigDecimal.ZERO
    var JW: BigDecimal = BigDecimal.ZERO
    var K: Int = 0
    var KFB: BigDecimal = BigDecimal.ZERO
    var KVSATZAN: BigDecimal = BigDecimal.ZERO
    var KZTAB: Int = 0
    var LSTJAHR: BigDecimal = BigDecimal.ZERO
    var LSTOSO: BigDecimal = BigDecimal.ZERO
    var LSTSO: BigDecimal = BigDecimal.ZERO
    var MIST: BigDecimal = BigDecimal.ZERO
    var PKPVAGZJ: BigDecimal = BigDecimal.ZERO
    var PVSATZAN: BigDecimal = BigDecimal.ZERO
    var RVSATZAN: BigDecimal = BigDecimal.ZERO
    var RW: BigDecimal = BigDecimal.ZERO
    var SAP: BigDecimal = BigDecimal.ZERO
    var SOLZFREI: BigDecimal = BigDecimal.ZERO
    var SOLZJ: BigDecimal = BigDecimal.ZERO
    var SOLZMIN: BigDecimal = BigDecimal.ZERO
    var SOLZSBMG: BigDecimal = BigDecimal.ZERO
    var SOLZSZVE: BigDecimal = BigDecimal.ZERO
    var ST: BigDecimal = BigDecimal.ZERO
    var ST1: BigDecimal = BigDecimal.ZERO
    var ST2: BigDecimal = BigDecimal.ZERO
    var VBEZB: BigDecimal = BigDecimal.ZERO
    var VBEZBSO: BigDecimal = BigDecimal.ZERO
    var VERGL: BigDecimal = BigDecimal.ZERO
    var VSPHB: BigDecimal = BigDecimal.ZERO
    var VSP: BigDecimal = BigDecimal.ZERO
    var VSPN: BigDecimal = BigDecimal.ZERO
    var VSPALV: BigDecimal = BigDecimal.ZERO
    var VSPKVPV: BigDecimal = BigDecimal.ZERO
    var VSPR: BigDecimal = BigDecimal.ZERO
    var W1STKL5: BigDecimal = BigDecimal.ZERO
    var W2STKL5: BigDecimal = BigDecimal.ZERO
    var W3STKL5: BigDecimal = BigDecimal.ZERO
    var X: BigDecimal = BigDecimal.ZERO
    var Y: BigDecimal = BigDecimal.ZERO
    var ZRE4: BigDecimal = BigDecimal.ZERO
    var ZRE4J: BigDecimal = BigDecimal.ZERO
    var ZRE4VP: BigDecimal = BigDecimal.ZERO
    var ZRE4VPR: BigDecimal = BigDecimal.ZERO
    var ZTABFB: BigDecimal = BigDecimal.ZERO
    var ZVBEZ: BigDecimal = BigDecimal.ZERO
    var ZVBEZJ: BigDecimal = BigDecimal.ZERO
    var ZVE: BigDecimal = BigDecimal.ZERO
    var ZX: BigDecimal = BigDecimal.ZERO
    var ZZX: BigDecimal = BigDecimal.ZERO

    companion object {
        private fun bd(v: Int): BigDecimal = BigDecimal.valueOf(v.toLong())
        private fun bd(v: Long): BigDecimal = BigDecimal.valueOf(v)
        private fun bd(v: Double): BigDecimal = BigDecimal.valueOf(v)
        val TAB1: Array<BigDecimal> = arrayOf(BigDecimal.ZERO, bd( 0.4), bd( 0.384), bd( 0.368), bd( 0.352), bd( 0.336), bd( 0.32), bd( 0.304), bd( 0.288), bd( 0.272), bd( 0.256), bd( 0.24), bd( 0.224), bd( 0.208), bd( 0.192), bd( 0.176), bd( 0.16), bd( 0.152), bd( 0.144), bd( 0.14), bd( 0.136), bd( 0.132), bd( 0.128), bd( 0.124), bd( 0.12), bd( 0.116), bd( 0.112), bd( 0.108), bd( 0.104), bd( 0.1), bd( 0.096), bd( 0.092), bd( 0.088), bd( 0.084), bd( 0.08), bd( 0.076), bd( 0.072), bd( 0.068), bd( 0.064), bd( 0.06), bd( 0.056), bd( 0.052), bd( 0.048), bd( 0.044), bd( 0.04), bd( 0.036), bd( 0.032), bd( 0.028), bd( 0.024), bd( 0.02), bd( 0.016), bd( 0.012), bd( 0.008), bd( 0.004), bd( 0))
        val TAB2: Array<BigDecimal> = arrayOf(BigDecimal.ZERO, bd( 3000), bd( 2880), bd( 2760), bd( 2640), bd( 2520), bd( 2400), bd( 2280), bd( 2160), bd( 2040), bd( 1920), bd( 1800), bd( 1680), bd( 1560), bd( 1440), bd( 1320), bd( 1200), bd( 1140), bd( 1080), bd( 1050), bd( 1020), bd( 990), bd( 960), bd( 930), bd( 900), bd( 870), bd( 840), bd( 810), bd( 780), bd( 750), bd( 720), bd( 690), bd( 660), bd( 630), bd( 600), bd( 570), bd( 540), bd( 510), bd( 480), bd( 450), bd( 420), bd( 390), bd( 360), bd( 330), bd( 300), bd( 270), bd( 240), bd( 210), bd( 180), bd( 150), bd( 120), bd( 90), bd( 60), bd( 30), bd( 0))
        val TAB3: Array<BigDecimal> = arrayOf(BigDecimal.ZERO, bd( 900), bd( 864), bd( 828), bd( 792), bd( 756), bd( 720), bd( 684), bd( 648), bd( 612), bd( 576), bd( 540), bd( 504), bd( 468), bd( 432), bd( 396), bd( 360), bd( 342), bd( 324), bd( 315), bd( 306), bd( 297), bd( 288), bd( 279), bd( 270), bd( 261), bd( 252), bd( 243), bd( 234), bd( 225), bd( 216), bd( 207), bd( 198), bd( 189), bd( 180), bd( 171), bd( 162), bd( 153), bd( 144), bd( 135), bd( 126), bd( 117), bd( 108), bd( 99), bd( 90), bd( 81), bd( 72), bd( 63), bd( 54), bd( 45), bd( 36), bd( 27), bd( 18), bd( 9), bd( 0))
        val TAB4: Array<BigDecimal> = arrayOf(BigDecimal.ZERO, bd( 0.4), bd( 0.384), bd( 0.368), bd( 0.352), bd( 0.336), bd( 0.32), bd( 0.304), bd( 0.288), bd( 0.272), bd( 0.256), bd( 0.24), bd( 0.224), bd( 0.208), bd( 0.192), bd( 0.176), bd( 0.16), bd( 0.152), bd( 0.144), bd( 0.14), bd( 0.136), bd( 0.132), bd( 0.128), bd( 0.124), bd( 0.12), bd( 0.116), bd( 0.112), bd( 0.108), bd( 0.104), bd( 0.1), bd( 0.096), bd( 0.092), bd( 0.088), bd( 0.084), bd( 0.08), bd( 0.076), bd( 0.072), bd( 0.068), bd( 0.064), bd( 0.06), bd( 0.056), bd( 0.052), bd( 0.048), bd( 0.044), bd( 0.04), bd( 0.036), bd( 0.032), bd( 0.028), bd( 0.024), bd( 0.02), bd( 0.016), bd( 0.012), bd( 0.008), bd( 0.004), bd( 0))
        val TAB5: Array<BigDecimal> = arrayOf(BigDecimal.ZERO, bd( 1900), bd( 1824), bd( 1748), bd( 1672), bd( 1596), bd( 1520), bd( 1444), bd( 1368), bd( 1292), bd( 1216), bd( 1140), bd( 1064), bd( 988), bd( 912), bd( 836), bd( 760), bd( 722), bd( 684), bd( 665), bd( 646), bd( 627), bd( 608), bd( 589), bd( 570), bd( 551), bd( 532), bd( 513), bd( 494), bd( 475), bd( 456), bd( 437), bd( 418), bd( 399), bd( 380), bd( 361), bd( 342), bd( 323), bd( 304), bd( 285), bd( 266), bd( 247), bd( 228), bd( 209), bd( 190), bd( 171), bd( 152), bd( 133), bd( 114), bd( 95), bd( 76), bd( 57), bd( 38), bd( 19), bd( 0))
        val ZAHL1: BigDecimal = BigDecimal.ONE
        val ZAHL2: BigDecimal = bd(2)
        val ZAHL5: BigDecimal = bd(5)
        val ZAHL7: BigDecimal = bd(7)
        val ZAHL12: BigDecimal = bd(12)
        val ZAHL100: BigDecimal = bd(100)
        val ZAHL360: BigDecimal = bd(360)
        val ZAHL500: BigDecimal = bd(500)
        val ZAHL700: BigDecimal = bd(700)
        val ZAHL1000: BigDecimal = bd(1000)
        val ZAHL10000: BigDecimal = bd(10000)
    }

    fun main() {
        MPARA()
        MRE4JL()
        VBEZBSO = BigDecimal.ZERO
        MRE4()
        MRE4ABZ()
        MBERECH()
        MSONST()
    }

    private fun MPARA() {
        BBGRVALV = bd(101400)
        AVSATZAN = bd(0.013)
        RVSATZAN = bd(0.093)
        BBGKVPV = bd(69750)
        KVSATZAN = (KVZ.divide(ZAHL2).divide(ZAHL100)).add(bd(0.07))
        if (PVS == 1) {
            PVSATZAN = bd(0.023)
        } else {
            PVSATZAN = bd(0.018)
        }
        if (PVZ == 1) {
            PVSATZAN = PVSATZAN.add(bd(0.006))
        } else {
            PVSATZAN = PVSATZAN.subtract(PVA.multiply(bd(0.0025)))
        }
        W1STKL5 = bd(14071)
        W2STKL5 = bd(34939)
        W3STKL5 = bd(222260)
        GFB = bd(12348)
        SOLZFREI = bd(20350)
    }

    private fun MRE4JL() {
        if (LZZ == 1) {
            ZRE4J = RE4.divide(ZAHL100, 2, RoundingMode.DOWN)
            ZVBEZJ = VBEZ.divide(ZAHL100, 2, RoundingMode.DOWN)
            JLFREIB = LZZFREIB.divide(ZAHL100, 2, RoundingMode.DOWN)
            JLHINZU = LZZHINZU.divide(ZAHL100, 2, RoundingMode.DOWN)
        } else {
            if (LZZ == 2) {
                ZRE4J = (RE4.multiply(ZAHL12)).divide(ZAHL100, 2, RoundingMode.DOWN)
                ZVBEZJ = (VBEZ.multiply(ZAHL12)).divide(ZAHL100, 2, RoundingMode.DOWN)
                JLFREIB = (LZZFREIB.multiply(ZAHL12)).divide(ZAHL100, 2, RoundingMode.DOWN)
                JLHINZU = (LZZHINZU.multiply(ZAHL12)).divide(ZAHL100, 2, RoundingMode.DOWN)
            } else {
                if (LZZ == 3) {
                    ZRE4J = (RE4.multiply(ZAHL360)).divide(ZAHL700, 2, RoundingMode.DOWN)
                    ZVBEZJ = (VBEZ.multiply(ZAHL360)).divide(ZAHL700, 2, RoundingMode.DOWN)
                    JLFREIB = (LZZFREIB.multiply(ZAHL360)).divide(ZAHL700, 2, RoundingMode.DOWN)
                    JLHINZU = (LZZHINZU.multiply(ZAHL360)).divide(ZAHL700, 2, RoundingMode.DOWN)
                } else {
                    ZRE4J = (RE4.multiply(ZAHL360)).divide(ZAHL100, 2, RoundingMode.DOWN)
                    ZVBEZJ = (VBEZ.multiply(ZAHL360)).divide(ZAHL100, 2, RoundingMode.DOWN)
                    JLFREIB = (LZZFREIB.multiply(ZAHL360)).divide(ZAHL100, 2, RoundingMode.DOWN)
                    JLHINZU = (LZZHINZU.multiply(ZAHL360)).divide(ZAHL100, 2, RoundingMode.DOWN)
                }
            }
        }
        if (af == 0) {
            f = 1.0
        }
    }

    private fun MRE4() {
        if (ZVBEZJ.compareTo(BigDecimal.ZERO) == 0) {
            FVBZ = BigDecimal.ZERO
            FVB = BigDecimal.ZERO
            FVBZSO = BigDecimal.ZERO
            FVBSO = BigDecimal.ZERO
        } else {
            if (VJAHR < 2006) {
                J = 1
            } else {
                if (VJAHR < 2058) {
                    J = VJAHR - 2004
                } else {
                    J = 54
                }
            }
            if (LZZ == 1) {
                VBEZB = (VBEZM.multiply(bd(ZMVB))).add(VBEZS)
                HFVB = TAB2[J].divide(ZAHL12).multiply(bd(ZMVB)).setScale(0, RoundingMode.UP)
                FVBZ = TAB3[J].divide(ZAHL12).multiply(bd(ZMVB)).setScale(0, RoundingMode.UP)
            } else {
                VBEZB = ((VBEZM.multiply(ZAHL12)).add(VBEZS)).setScale(2, RoundingMode.DOWN)
                HFVB = TAB2[J]
                FVBZ = TAB3[J]
            }
            FVB = ((VBEZB.multiply(TAB1[J]))).divide(ZAHL100).setScale(2, RoundingMode.UP)
            if (FVB.compareTo(HFVB) == 1) {
                FVB = HFVB
            }
            if (FVB.compareTo(ZVBEZJ) == 1) {
                FVB = ZVBEZJ
            }
            FVBSO = (FVB.add((VBEZBSO.multiply(TAB1[J])).divide(ZAHL100))).setScale(2, RoundingMode.UP)
            if (FVBSO.compareTo(TAB2[J]) == 1) {
                FVBSO = TAB2[J]
            }
            HFVBZSO = (((VBEZB.add(VBEZBSO)).divide(ZAHL100)).subtract(FVBSO)).setScale(2, RoundingMode.DOWN)
            FVBZSO = (FVBZ.add((VBEZBSO).divide(ZAHL100))).setScale(0, RoundingMode.UP)
            if (FVBZSO.compareTo(HFVBZSO) == 1) {
                FVBZSO = HFVBZSO.setScale(0, RoundingMode.UP)
            }
            if (FVBZSO.compareTo(TAB3[J]) == 1) {
                FVBZSO = TAB3[J]
            }
            HFVBZ = ((VBEZB.divide(ZAHL100)).subtract(FVB)).setScale(2, RoundingMode.DOWN)
            if (FVBZ.compareTo(HFVBZ) == 1) {
                FVBZ = HFVBZ.setScale(0, RoundingMode.UP)
            }
        }
        MRE4ALTE()
    }

    private fun MRE4ALTE() {
        if (ALTER1 == 0) {
            ALTE = BigDecimal.ZERO
        } else {
            if (AJAHR < 2006) {
                K = 1
            } else {
                if (AJAHR < 2058) {
                    K = AJAHR - 2004
                } else {
                    K = 54
                }
            }
            BMG = ZRE4J.subtract(ZVBEZJ)
            ALTE = (BMG.multiply(TAB4[K])).setScale(0, RoundingMode.UP)
            HBALTE = TAB5[K]
            if (ALTE.compareTo(HBALTE) == 1) {
                ALTE = HBALTE
            }
        }
    }

    private fun MRE4ABZ() {
        ZRE4 = (ZRE4J.subtract(FVB).subtract(ALTE).subtract(JLFREIB).add(JLHINZU)).setScale(2, RoundingMode.DOWN)
        if (ZRE4.compareTo(BigDecimal.ZERO) == -1) {
            ZRE4 = BigDecimal.ZERO
        }
        ZRE4VP = ZRE4J
        ZVBEZ = ZVBEZJ.subtract(FVB).setScale(2, RoundingMode.DOWN)
        if (ZVBEZ.compareTo(BigDecimal.ZERO) == -1) {
            ZVBEZ = BigDecimal.ZERO
        }
    }

    private fun MBERECH() {
        MZTABFB()
        VFRB = ((ANP.add(FVB.add(FVBZ))).multiply(ZAHL100)).setScale(0, RoundingMode.DOWN)
        MLSTJAHR()
        WVFRB = ((ZVE.subtract(GFB)).multiply(ZAHL100)).setScale(0, RoundingMode.DOWN)
        if (WVFRB.compareTo(BigDecimal.ZERO) == -1) {
            WVFRB = BigDecimal.ZERO
        }
        LSTJAHR = (ST.multiply(bd(f))).setScale(0,RoundingMode.DOWN)
        UPLSTLZZ()
        if (ZKF.compareTo(BigDecimal.ZERO) == 1) {
            ZTABFB = ZTABFB.add(KFB)
            MRE4ABZ()
            MLSTJAHR()
            JBMG = (ST.multiply(bd(f))).setScale(0,RoundingMode.DOWN)
        } else {
            JBMG = LSTJAHR
        }
        MSOLZ()
    }

    private fun MZTABFB() {
        ANP = BigDecimal.ZERO
        if (ZVBEZ.compareTo(BigDecimal.ZERO) >= 0 && ZVBEZ.compareTo(FVBZ) == -1) {
            FVBZ = bd(ZVBEZ.toLong())
        }
        if (STKL < 6) {
            if (ZVBEZ.compareTo(BigDecimal.ZERO) == 1) {
                if ((ZVBEZ.subtract(FVBZ)).compareTo(bd(102)) == -1) {
                    ANP = (ZVBEZ.subtract(FVBZ)).setScale(0, RoundingMode.UP)
                } else {
                    ANP = bd(102)
                }
            }
        } else {
            FVBZ = BigDecimal.ZERO
            FVBZSO = BigDecimal.ZERO
        }
        if (STKL < 6) {
            if (ZRE4.compareTo(ZVBEZ) == 1) {
                if (ZRE4.subtract(ZVBEZ).compareTo(bd(1230)) == -1) {
                    ANP = ANP.add(ZRE4).subtract(ZVBEZ).setScale(0,RoundingMode.UP)
                } else {
                    ANP = ANP.add(bd(1230))
                }
            }
        }
        KZTAB = 1
        if (STKL == 1) {
            SAP = bd(36)
            KFB = (ZKF.multiply(bd(9756))).setScale(0, RoundingMode.DOWN)
        } else {
            if (STKL == 2) {
                EFA = bd(4260)
                SAP = bd(36)
                KFB = (ZKF.multiply(bd(9756))).setScale(0, RoundingMode.DOWN)
            } else {
                if (STKL == 3) {
                    KZTAB = 2
                    SAP = bd(36)
                    KFB = (ZKF.multiply(bd(9756))).setScale(0, RoundingMode.DOWN)
                } else {
                    if (STKL == 4) {
                        SAP = bd(36)
                        KFB = (ZKF.multiply(bd(4878))).setScale(0, RoundingMode.DOWN)
                    } else {
                        if (STKL == 5) {
                            SAP = bd(36)
                            KFB = BigDecimal.ZERO
                        } else {
                            KFB = BigDecimal.ZERO
                        }
                    }
                }
            }
        }
        ZTABFB = (EFA.add(ANP).add(SAP).add(FVBZ)).setScale(2, RoundingMode.DOWN)
    }

    private fun MLSTJAHR() {
        UPEVP()
        ZVE = ZRE4.subtract(ZTABFB).subtract(VSP)
        UPMLST()
    }

    private fun UPLSTLZZ() {
        JW = LSTJAHR.multiply(ZAHL100)
        UPANTEIL()
        LSTLZZ = ANTEIL1
    }

    private fun UPMLST() {
        if (ZVE.compareTo(ZAHL1) == -1) {
            ZVE = BigDecimal.ZERO
            X = BigDecimal.ZERO
        } else {
            X = (ZVE.divide(bd(KZTAB))).setScale(0, RoundingMode.DOWN)
        }
        if (STKL < 5) {
            UPTAB26()
        } else {
            MST5_6()
        }
    }

    private fun UPEVP() {
        if (KRV == 1) {
            VSPR = BigDecimal.ZERO
        } else {
            if (ZRE4VP.compareTo(BBGRVALV) == 1) {
                ZRE4VPR = BBGRVALV
            } else {
                ZRE4VPR = ZRE4VP
            }
            VSPR = (ZRE4VPR.multiply(RVSATZAN)).setScale(2,RoundingMode.DOWN)
        }
        MVSPKVPV()
        if (ALV == 1) {
        } else {
            if (STKL == 6) {
            } else {
                MVSPHB()
            }
        }
    }

    private fun MVSPKVPV() {
        if (ZRE4VP.compareTo(BBGKVPV) == 1) {
            ZRE4VPR = BBGKVPV
        } else {
            ZRE4VPR = ZRE4VP
        }
        if (PKV > 0) {
            if (STKL == 6) {
                VSPKVPV = BigDecimal.ZERO
            } else {
                PKPVAGZJ = PKPVAGZ.multiply(ZAHL12).divide(ZAHL100).setScale(2,RoundingMode.DOWN)
                VSPKVPV = PKPV.multiply(ZAHL12).divide(ZAHL100).setScale(2, RoundingMode.DOWN)
                VSPKVPV = VSPKVPV.subtract(PKPVAGZJ)
                if (VSPKVPV.compareTo(BigDecimal.ZERO) == -1) {
                    VSPKVPV = BigDecimal.ZERO
                }
            }
        } else {
            VSPKVPV = ZRE4VPR.multiply(KVSATZAN.add(PVSATZAN)).setScale(2, RoundingMode.DOWN)
        }
        VSP = VSPKVPV.add(VSPR).setScale(0, RoundingMode.UP)
    }

    private fun MVSPHB() {
        if (ZRE4VP.compareTo(BBGRVALV) == 1) {
            ZRE4VPR = BBGRVALV
        } else {
            ZRE4VPR = ZRE4VP
        }
        VSPALV = AVSATZAN.multiply(ZRE4VPR).setScale(2, RoundingMode.DOWN)
        VSPHB = VSPALV.add(VSPKVPV).setScale(2, RoundingMode.DOWN)
        if (VSPHB.compareTo(bd(1900)) == 1) {
            VSPHB = bd(1900)
        }
        VSPN = VSPR.add(VSPHB).setScale(0, RoundingMode.UP)
        if (VSPN.compareTo(VSP) == 1) {
            VSP = VSPN
        }
    }

    private fun MST5_6() {
        ZZX = X
        if (ZZX.compareTo(W2STKL5) == 1) {
            ZX = W2STKL5
            UP5_6()
            if (ZZX.compareTo(W3STKL5) == 1) {
                ST = (ST.add((W3STKL5.subtract(W2STKL5)).multiply(bd(0.42)))).setScale(0, RoundingMode.DOWN)
                ST = (ST.add((ZZX.subtract(W3STKL5)).multiply(bd(0.45)))).setScale(0, RoundingMode.DOWN)
            } else {
                ST = (ST.add((ZZX.subtract(W2STKL5)).multiply(bd(0.42)))).setScale(0, RoundingMode.DOWN)
            }
        } else {
            ZX = ZZX
            UP5_6()
            if (ZZX.compareTo(W1STKL5) == 1) {
                VERGL = ST
                ZX = W1STKL5
                UP5_6()
                HOCH = (ST.add((ZZX.subtract(W1STKL5)).multiply(bd(0.42)))).setScale(0, RoundingMode.DOWN)
                if (HOCH.compareTo(VERGL) == -1) {
                    ST = HOCH
                } else {
                    ST = VERGL
                }
            }
        }
    }

    private fun UP5_6() {
        X = (ZX.multiply(bd(1.25))).setScale(0, RoundingMode.DOWN)
        UPTAB26()
        ST1 = ST
        X = (ZX.multiply(bd(0.75))).setScale(0, RoundingMode.DOWN)
        UPTAB26()
        ST2 = ST
        DIFF = (ST1.subtract(ST2)).multiply(ZAHL2)
        MIST = (ZX.multiply(bd(0.14))).setScale(0, RoundingMode.DOWN)
        if (MIST.compareTo(DIFF) == 1) {
            ST = MIST
        } else {
            ST = DIFF
        }
    }

    private fun MSOLZ() {
        SOLZFREI = (SOLZFREI.multiply(bd(KZTAB)))
        if (JBMG.compareTo(SOLZFREI) == 1) {
            SOLZJ = (JBMG.multiply(bd(5.5))).divide(ZAHL100).setScale(2, RoundingMode.DOWN)
            SOLZMIN = (JBMG.subtract(SOLZFREI)).multiply(bd(11.9)).divide(ZAHL100).setScale(2, RoundingMode.DOWN)
            if (SOLZMIN.compareTo(SOLZJ) == -1) {
                SOLZJ = SOLZMIN
            }
            JW = SOLZJ.multiply(ZAHL100).setScale(0, RoundingMode.DOWN)
            UPANTEIL()
            SOLZLZZ = ANTEIL1
        } else {
            SOLZLZZ = BigDecimal.ZERO
        }
        if (R > 0) {
            JW = JBMG.multiply(ZAHL100)
            UPANTEIL()
            BK = ANTEIL1
        } else {
            BK = BigDecimal.ZERO
        }
    }

    private fun UPANTEIL() {
        if (LZZ == 1) {
            ANTEIL1 = JW
        } else {
            if (LZZ == 2) {
                ANTEIL1 = JW.divide(ZAHL12, 0, RoundingMode.DOWN)
            } else {
                if (LZZ == 3) {
                    ANTEIL1 = (JW.multiply(ZAHL7)).divide(ZAHL360, 0, RoundingMode.DOWN)
                } else {
                    ANTEIL1 = JW.divide(ZAHL360, 0, RoundingMode.DOWN)
                }
            }
        }
    }

    private fun MSONST() {
        LZZ = 1
        if (ZMVB == 0) {
            ZMVB = 12
        }
        if (SONSTB.compareTo(BigDecimal.ZERO) == 0 && MBV.compareTo(BigDecimal.ZERO) == 0) {
            LSTSO = BigDecimal.ZERO
            STS = BigDecimal.ZERO
            SOLZS = BigDecimal.ZERO
            BKS = BigDecimal.ZERO
        } else {
            MOSONST()
            ZRE4J = ((JRE4.add(SONSTB)).divide(ZAHL100)).setScale(2, RoundingMode.DOWN)
            ZVBEZJ = ((JVBEZ.add(VBS)).divide(ZAHL100)).setScale(2, RoundingMode.DOWN)
            VBEZBSO = STERBE
            MRE4SONST()
            MLSTJAHR()
            WVFRBM = (ZVE.subtract(GFB)).multiply(ZAHL100).setScale(2,RoundingMode.DOWN)
            if (WVFRBM.compareTo(BigDecimal.ZERO) == -1) {
                WVFRBM = BigDecimal.ZERO
            }
            LSTSO = ST.multiply(ZAHL100)
            STS = LSTSO.subtract(LSTOSO).multiply(bd(f)).divide(ZAHL100, 0, RoundingMode.DOWN).multiply(ZAHL100)
            STSMIN()
        }
    }

    private fun STSMIN() {
        if (STS.compareTo(BigDecimal.ZERO) == -1) {
            if (MBV.compareTo(BigDecimal.ZERO) == 0) {
            } else {
                LSTLZZ = LSTLZZ.add(STS)
                if (LSTLZZ.compareTo(BigDecimal.ZERO) == -1) {
                    LSTLZZ = BigDecimal.ZERO
                }
                SOLZLZZ = SOLZLZZ.add(STS.multiply(bd(5.5).divide(ZAHL100))).setScale(0, RoundingMode.DOWN)
                if (SOLZLZZ.compareTo(BigDecimal.ZERO) == -1) {
                    SOLZLZZ = BigDecimal.ZERO
                }
                BK = BK.add(STS)
                if (BK.compareTo(BigDecimal.ZERO) == -1) {
                    BK = BigDecimal.ZERO
                }
            }
            STS = BigDecimal.ZERO
            SOLZS = BigDecimal.ZERO
        } else {
            MSOLZSTS()
        }
        if (R > 0) {
            BKS = STS
        } else {
            BKS = BigDecimal.ZERO
        }
    }

    private fun MSOLZSTS() {
        if (ZKF.compareTo(BigDecimal.ZERO) == 1) {
            SOLZSZVE = ZVE.subtract(KFB)
        } else {
            SOLZSZVE = ZVE
        }
        if (SOLZSZVE.compareTo(BigDecimal.ONE) == -1) {
            SOLZSZVE = BigDecimal.ZERO
            X = BigDecimal.ZERO
        } else {
            X = SOLZSZVE.divide(bd(KZTAB), 0, RoundingMode.DOWN)
        }
        if (STKL < 5) {
            UPTAB26()
        } else {
            MST5_6()
        }
        SOLZSBMG = ST.multiply(bd(f)).setScale(0,RoundingMode.DOWN)
        if (SOLZSBMG.compareTo(SOLZFREI) == 1) {
            SOLZS = STS.multiply(bd(5.5)).divide(ZAHL100, 0, RoundingMode.DOWN)
        } else {
            SOLZS = BigDecimal.ZERO
        }
    }

    private fun MOSONST() {
        ZRE4J = (JRE4.divide(ZAHL100)).setScale(2, RoundingMode.DOWN)
        ZVBEZJ = (JVBEZ.divide(ZAHL100)).setScale(2, RoundingMode.DOWN)
        JLFREIB = JFREIB.divide(ZAHL100, 2, RoundingMode.DOWN)
        JLHINZU = JHINZU.divide(ZAHL100, 2, RoundingMode.DOWN)
        MRE4()
        MRE4ABZ()
        ZRE4VP = ZRE4VP.subtract(JRE4ENT.divide(ZAHL100))
        MZTABFB()
        VFRBS1 = ((ANP.add(FVB.add(FVBZ))).multiply(ZAHL100)).setScale(2,RoundingMode.DOWN)
        MLSTJAHR()
        WVFRBO = ((ZVE.subtract(GFB)).multiply(ZAHL100)).setScale(2, RoundingMode.DOWN)
        if (WVFRBO.compareTo(BigDecimal.ZERO) == -1) {
            WVFRBO = BigDecimal.ZERO
        }
        LSTOSO = ST.multiply(ZAHL100)
    }

    private fun MRE4SONST() {
        MRE4()
        FVB = FVBSO
        MRE4ABZ()
        ZRE4VP = ZRE4VP.add(MBV.divide(ZAHL100)).subtract(JRE4ENT.divide(ZAHL100)).subtract(SONSTENT.divide(ZAHL100))
        FVBZ = FVBZSO
        MZTABFB()
        VFRBS2 = ((((ANP.add(FVB).add(FVBZ))).multiply(ZAHL100))).subtract(VFRBS1)
    }

    private fun UPTAB26() {
        if (X.compareTo(GFB.add(ZAHL1)) == -1) {
            ST = BigDecimal.ZERO
        } else {
            if (X.compareTo(bd(17800)) == -1) {
                Y = (X.subtract(GFB)).divide(ZAHL10000, 6,RoundingMode.DOWN)
                RW = Y.multiply(bd(914.51))
                RW = RW.add(bd(1400))
                ST = (RW.multiply(Y)).setScale(0, RoundingMode.DOWN)
            } else {
                if (X.compareTo(bd(69879)) == -1) {
                    Y = (X.subtract(bd(17799))).divide(ZAHL10000, 6, RoundingMode.DOWN)
                    RW = Y.multiply(bd(173.1))
                    RW = RW.add(bd(2397))
                    RW = RW.multiply(Y)
                    ST = (RW.add(bd(1034.87))).setScale(0, RoundingMode.DOWN)
                } else {
                    if (X.compareTo(bd(277826)) == -1) {
                        ST = ((X.multiply(bd(0.42))).subtract(bd(11135.63))).setScale(0, RoundingMode.DOWN)
                    } else {
                        ST = ((X.multiply(bd(0.45))).subtract(bd(19470.38))).setScale(0, RoundingMode.DOWN)
                    }
                }
            }
        }
        ST = ST.multiply(bd(KZTAB))
    }
}
