#!/usr/bin/env python3
"""Translate the BMF's Lohnsteuer PAP (XML pseudo-code) into one Kotlin class.

The Bundesministerium der Finanzen publishes the payroll-tax algorithm each year as a
"Programmablaufplan" in XML whose expressions are Java (java.math.BigDecimal). This script is
the only author of core/src/main/kotlin/.../tax/Lohnsteuer<year>.kt: it copies the PAP's
variables, constants, methods and control flow one to one, rewriting only what Kotlin spells
differently from Java (array literals, Int/Long/Double to BigDecimal.valueOf, Number accessors,
the deprecated BigDecimal.ROUND_* ints). Nothing about the tax is decided here.

    python3 core/tools/pap2kt.py core/pap/Lohnsteuer2026.xml > <the .kt it writes>

test/test-search-shell.sh re-runs it and fails when the committed Kotlin differs, so the
generated file can never be edited by hand or drift from the XML it claims to come from.
"""
import re
import sys
import xml.etree.ElementTree as ET

KT_TYPES = {"int": "Int", "double": "Double", "BigDecimal": "BigDecimal", "BigDecimal[]": "Array<BigDecimal>"}


def expr(java: str) -> str:
    s = java.strip()
    s = re.sub(r"BigDecimal\.ROUND_(\w+)", r"RoundingMode.\1", s)
    s = re.sub(r"BigDecimal\.valueOf\s*\(", "bd(", s)
    s = s.replace(".longValue()", ".toLong()").replace(".intValue()", ".toInt()").replace(".doubleValue()", ".toDouble()")
    s = re.sub(r"new\s+BigDecimal\s*\(", "BigDecimal(", s)
    s = re.sub(r"(\w)\s+\(", r"\1(", s)
    if s.startswith("{") and s.endswith("}"):
        s = "arrayOf(" + s[1:-1].strip() + ")"
    return s


def default(kind: str, value) -> str:
    if value is not None:
        v = expr(value)
        if kind == "double" and re.fullmatch(r"-?\d+", v):
            v += ".0"
        return v
    return {"int": "0", "double": "0.0", "BigDecimal": "BigDecimal.ZERO"}[kind]


def main(path: str) -> None:
    root = ET.parse(path).getroot()
    name = root.get("name")
    types = {}
    out = []
    w = out.append

    def stmt(el, ind):
        pad = "    " * ind
        for c in el:
            if c.tag == "EVAL":
                target, rhs = c.get("exec").split("=", 1)
                target = target.strip()
                rhs = expr(rhs)
                if types.get(target) == "double" and re.fullmatch(r"-?\d+", rhs):
                    rhs += ".0"
                w(f"{pad}{target} = {rhs}")
            elif c.tag == "EXECUTE":
                w(f"{pad}{c.get('method')}()")
            elif c.tag == "IF":
                w(f"{pad}if ({expr(c.get('expr'))}) {{")
                then = c.find("THEN")
                if then is not None:
                    stmt(then, ind + 1)
                other = c.find("ELSE")
                if other is not None and len(other):
                    w(f"{pad}}} else {{")
                    stmt(other, ind + 1)
                w(f"{pad}}}")
            elif c.tag in ("THEN", "ELSE"):
                raise SystemExit(f"unexpected {c.tag} outside IF")
            else:
                raise SystemExit(f"unknown PAP statement <{c.tag}>")

    variables = root.find("VARIABLES")
    w(f"// GENERATED by core/tools/pap2kt.py from core/pap/{name}.xml (BMF, {path_stand(path)}). Do not edit:")
    w("// test/test-search-shell.sh regenerates it and fails on any difference.")
    w('@file:Suppress("LocalVariableName", "PropertyName", "FunctionName", "ObjectPropertyName", "unused", "RedundantExplicitType", "NAME_SHADOWING")')
    w("")
    w("package com.diegonmarcos.cloudsearch.core.tax")
    w("")
    w("import java.math.BigDecimal")
    w("import java.math.RoundingMode")
    w("")
    w(f"/** The BMF's {name} Programmablaufplan, statement for statement. Set the inputs, call [main], read the outputs. */")
    w(f"class {name} {{")
    for section in ("INPUTS", "OUTPUTS", "INTERNALS"):
        for group in variables.iter(section):
            for v in group:
                if v.tag not in ("INPUT", "OUTPUT", "INTERNAL"):
                    continue
                kind = v.get("type")
                types[v.get("name")] = kind
                w(f"    var {v.get('name')}: {KT_TYPES[kind]} = {default(kind, v.get('default'))}")
    w("")
    w("    companion object {")
    w("        private fun bd(v: Int): BigDecimal = BigDecimal.valueOf(v.toLong())")
    w("        private fun bd(v: Long): BigDecimal = BigDecimal.valueOf(v)")
    w("        private fun bd(v: Double): BigDecimal = BigDecimal.valueOf(v)")
    for c in root.iter("CONSTANT"):
        if c.tag != "CONSTANT":
            continue
        kind = c.get("type")
        types[c.get("name")] = kind
        w(f"        val {c.get('name')}: {KT_TYPES[kind]} = {expr(c.get('value'))}")
    w("    }")
    methods = root.find("METHODS")
    w("")
    w("    fun main() {")
    stmt(methods.find("MAIN"), 2)
    w("    }")
    for m in methods.findall("METHOD"):
        w("")
        w(f"    private fun {m.get('name')}() {{")
        stmt(m, 2)
        w("    }")
    w("}")
    print("\n".join(out))


def path_stand(path: str) -> str:
    m = re.search(r"Stand:\s*([0-9-]+\s*[0-9:]*)", open(path, encoding="utf-8-sig").read())
    return "Stand " + m.group(1).strip() if m else "no Stand line"


if __name__ == "__main__":
    main(sys.argv[1])
