#!/usr/bin/env python3
"""cloud_android_workflow_paths.py -- manages the ``paths:`` header of ship-*.yml.

Single source of truth for the paths-header region. Imported by
cloud-android-ship-repo-workflow-engine.sh (the generator) and by its regression
tester (1_cicd/src/scripts/test/test-workflow-header-fence.test.sh), so the code
under test and the code in production are the same file.

Task #483: the old engine recognised its own header by exact text match against
the CURRENT header and emitted every other comment as the author's. A single
re-wrapped header line stopped matching, was reclassified as authored, and was
re-emitted below the new header on every run forever -- the generator laundering
its own stale output into hand-written content.

Post-hoc recognition cannot fix that (the measured options either half-work or
can fire on real authored prose), so we mark what we own EXPLICITLY with begin/
end fence markers and replace the whole fenced region on every run. Authored
comments live after the END marker and are carried through verbatim.

One-time migration: none of the baked-in files carry markers yet, so on the
first run over an unfenced block we untangle today's stranded lines from real
author prose with a bounded heuristic, then write the fence so it never runs
again. See test-workflow-header-fence.test.sh for the mutation-proofing.
"""
import re

BEG = "      # ── MANAGED-PATHS-HEADER: regenerated by cloud-android-ship-repo-workflow-engine.sh ──"
END = "      # ── end MANAGED-PATHS-HEADER ──"

APP_SHAPE = re.compile(r'^#\s+\S+/build\.json::modules declares is added automatically, dead$')
ENTRY_RE = re.compile(r'^\s*- "')


def make_header(app):
    """The 12 managed lines exactly as shipped. Only the app-name line varies."""
    # Byte-for-byte the header the engine has always emitted (em dashes U+2014).
    return [
        "      # MANAGED by cloud-android-ship-repo-workflow-engine.sh: every dir",
        "      # %s/build.json::modules declares is added automatically, dead" % app,
        "      # entries are dropped, and cloud-android-source-identity.sh hashes",
        "      # this list \u2014 so nothing can trigger a build the publish gate does",
        "      # not weigh. Extra entries no module map can express",
        "      # (settings.gradle.kts references, scan roots) are kept: add them",
        "      # here and they stay.",
        "      # ONE path is watched here and deliberately NOT hashed: the",
        "      # tester directory build.json::tests.shell.dir declares. A tester",
        "      # edit must START a run (it is the only pipeline that executes",
        "      # that tester) and must NOT publish an APK (it changed no bytes).",
        "      # The gate skips it, so the run costs the test step alone.",
    ]


def _statics():
    return [l for l in make_header("APP") if not APP_SHAPE.match(l.strip())]


def _is_current_header_line(l):
    s = l.strip()
    for h in make_header("APP"):
        if h.strip() == s:
            return True
    return bool(APP_SHAPE.match(s))


def _tokens(text):
    return set(re.findall(r"[a-zA-Z0-9]+", text.lower()))


def stale_overlap(text):
    """Fraction of a line's tokens also present in the static header prose."""
    H = set()
    for s in _statics():
        H |= _tokens(s)
    t = _tokens(re.sub(r"^#\s*", "", text))
    return (len(t & H) / len(t)) if t else 0.0


STALE_THRESHOLD = 0.85


def _drop_indexes(comments):
    """Managed comment indexes in an UNFENCED block (for the one-time migration).

    Returns (drop_set, stopped_before_fence): the current-header lines and any
    contiguous stale-fragment run immediately beneath them.
    """
    drop = set()
    i = 0
    while i < len(comments):
        if _is_current_header_line(comments[i]):
            drop.add(i)
            i += 1
        else:
            break
    while i < len(comments):
        s = comments[i].strip()
        if not s.startswith("#"):
            break
        if stale_overlap(s) >= STALE_THRESHOLD:
            drop.add(i)
            i += 1
        else:
            break
    return drop


def _split(region_lines):
    comments = []
    for l in region_lines:
        if ENTRY_RE.match(l):
            continue
        comments.append(l)
    return comments


# ── #836: build inputs hashed by the publish gate but NOT watched per push ──
# A shared lib compiled into many apps used to sit in every one of their push
# lists, so one lib edit started a ship run per consumer (700ab854: 12). Those
# inputs now live INSIDE the fence as comment lines: GitHub never sees them, so
# a push to the lib does not start this workflow, while
# cloud-android-source-identity.sh still hashes them (a dispatched run still
# publishes when they moved) and fleet-refresh.yml reads them to decide which
# apps it ships on its schedule.
DEFERRED_INTRO = [
    "      # #870 build inputs HASHED but NOT watched per push: every engine lib",
    "      # (its Cloud-Lib APK ships alone, apps bind it at runtime), each static",
    "      # lib this app is not the primary consumer of",
    "      # (1_cicd/src/data/lib-primary-consumers.json), cross-app dirs, shared",
    "      # data manifests and this workflow file. fleet-refresh.yml (schedule",
    "      # only) ships the app for a moved static lib or cross-app dir.",
]
DEFERRED_PREFIX = '      #   input: "'
DEFERRED_RE = re.compile(r'^      #   input: "([^"]+)"\s*$', re.M)


def deferred_inputs(text):
    """The deferred (hashed, not push-watched) inputs of a workflow's text."""
    return DEFERRED_RE.findall(text)


def rewrite_paths_block(region_lines, final_entries, app, deferred=()):
    header = make_header(app)
    if deferred:
        header = header + DEFERRED_INTRO + [DEFERRED_PREFIX + d + '"' for d in deferred]
    comments = _split(region_lines)

    B = BEG.strip()
    E = END.strip()
    has_beg = any(l.strip() == B for l in comments)
    keep = []
    if has_beg:
        infence = False
        for l in comments:
            s = l.strip()
            if s == B:
                infence = True
                continue
            if s == E:
                infence = False
                continue
            if not infence:
                keep.append(l)
    else:
        drop = _drop_indexes(comments)
        keep = [c for i, c in enumerate(comments) if i not in drop]

    block = ["    paths:"] + [BEG] + header + [END] + keep
    block += ["      - \"%s\"" % e for e in final_entries]
    return block

# ── #870: the rebuild-isolation rule, in ONE place ──────────────────────────
# An app ships only on its own dir (+ its fork engine + explicit_inputs); a
# shared lib that has a lib APK ships that APK only; shared manifests and other
# apps' dirs are hashed, never watched; fleet-refresh ships on cross-app source
# dirs only. Declaration: 1_cicd/src/data/rebuild-isolation.json.
import fnmatch, json, os

ISOLATION = "1_cicd/src/data/rebuild-isolation.json"


def isolation(root):
    return json.load(open(os.path.join(root, ISOLATION)))


def lib_apk_modules(root):
    """Shared libs that ship their own APK: a dir under libs/ with a build.gradle
    that lib-apks/build.json::lib_apks.exclude does not name."""
    libs = os.path.join(root, "ab_cloud-libs-shared/libs")
    try:
        excl = set(json.load(open(os.path.join(root, "ab_cloud-libs-shared/lib-apks/build.json")))["lib_apks"].get("exclude", {}))
    except (OSError, ValueError, KeyError):
        excl = set()
    return {d for d in os.listdir(libs) if os.path.isfile(os.path.join(libs, d, "build.gradle"))} - excl


def is_manifest(root, path):
    return any(fnmatch.fnmatchcase(path, g) for g in isolation(root).get("manifests", []))


def refresh_input(root, path):
    """True when a DEFERRED input may make fleet-refresh ship the app: a source
    dir of another app, not a lib, not a manifest, not a workflow file."""
    p = path.rstrip("*").rstrip("/")
    if p.startswith("ab_cloud-libs-shared/libs/"):
        return p.rsplit("/", 1)[-1] not in lib_apk_modules(root)   # a moved ENGINE ships its lib APK, never an app
    return not (p.startswith("1_cicd/") or is_manifest(root, path))
