#!/usr/bin/env python3
"""cloud-code: resolve the fleet ids nav.json names into launchable targets (#562).

nav.json::myterminal.target is a fleet application id (build.json::name of a
sibling app in cloud-u-android), never a package. This derives, from that app's
own declarations and nothing else:
  package  = <app>/build.json::android.application_id
  activity = the LAUNCHER activity of <app>/<gradle_module>/src/main/AndroidManifest.xml,
             a leading '.' resolved against the module's gradle `namespace`.
It writes src/cloud/targets.gen.json (gitignored), which the web bundle imports.
A target that resolves to nothing FAILS the build: a MyTerminal button that
launches a package that does not exist is the bug this replaces.

usage: resolve-targets.py <app-root> [--out FILE] [--print]
"""
import glob
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

ANDROID = "{http://schemas.android.com/apk/res/android}"


def resolve(app_root, fleet_id):
    repo = os.path.dirname(os.path.abspath(app_root))
    hits = []
    for bj in sorted(glob.glob(os.path.join(repo, "*", "build.json"))):
        try:
            data = json.load(open(bj))
        except (OSError, ValueError):
            continue
        if data.get("name") == fleet_id:
            hits.append((os.path.dirname(bj), data))
    if len(hits) != 1:
        raise SystemExit("resolve-targets: fleet id %r matches %d apps (need exactly 1)" % (fleet_id, len(hits)))
    app_dir, data = hits[0]
    package = (data.get("android") or {}).get("application_id")
    if not package:
        raise SystemExit("resolve-targets: %s/build.json has no android.application_id" % os.path.basename(app_dir))
    module = (data.get("android") or {}).get("gradle_module") or "app"
    manifest = os.path.join(app_dir, module, "src", "main", "AndroidManifest.xml")
    gradle = os.path.join(app_dir, module, "build.gradle")
    namespace = None
    if os.path.isfile(gradle):
        m = re.search(r"""^\s*namespace\s*[=(]?\s*['"]([\w.]+)['"]""", open(gradle).read(), re.M)
        namespace = m and m.group(1)
    namespace = namespace or package
    launcher = None
    for act in ET.parse(manifest).getroot().iter("activity"):
        for f in act.iter("intent-filter"):
            actions = {a.get(ANDROID + "name") for a in f.iter("action")}
            cats = {c.get(ANDROID + "name") for c in f.iter("category")}
            if "android.intent.action.MAIN" in actions and "android.intent.category.LAUNCHER" in cats:
                launcher = act.get(ANDROID + "name")
    if not launcher:
        raise SystemExit("resolve-targets: no LAUNCHER activity in %s" % os.path.relpath(manifest, repo))
    activity = namespace + launcher if launcher.startswith(".") else launcher
    return {"id": fleet_id, "app_dir": os.path.basename(app_dir), "package": package, "activity": activity}


def main(argv):
    if len(argv) < 2:
        raise SystemExit(__doc__)
    app_root = argv[1]
    nav = json.load(open(os.path.join(app_root, "src", "cloud", "nav.json")))
    out = {"_doc": "GENERATED by tools/resolve-targets.py from nav.json + the fleet. Do not edit.",
           "myterminal": resolve(app_root, nav["myterminal"]["target"])}
    text = json.dumps(out, indent=2) + "\n"
    if "--print" in argv:
        sys.stdout.write(text)
    if "--out" in argv:
        open(argv[argv.index("--out") + 1], "w").write(text)


if __name__ == "__main__":
    main(sys.argv)
