#!/usr/bin/env python3
"""Phosphor SVG -> Android vector drawable, for the icons app/tools/phosphor.json lists (#797).

Each Phosphor icon is one <path> on a 256x256 viewBox, so the conversion is the path data copied
into a <vector>. The tint comes from Compose (Icon's tint), so the fill colour here is irrelevant.
Run from anywhere: python3 ac_cloud-search/app/tools/phosphor2vd.py
`--launcher` writes only the app icon (phosphor.json::launcher) from the drawables on disk.
"""
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "src", "main", "res")
OUT = os.path.join(RES, "drawable")
URL = "https://unpkg.com/@phosphor-icons/core@{version}/assets/{weight}/{name}.svg"


def drawable(svg: str, source: str) -> str:
    if 'viewBox="0 0 256 256"' not in svg:
        raise ValueError(f"{source}: not a 256x256 Phosphor icon")
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if len(paths) != 1 or re.search(r"<(?!/?svg|path)[a-z]", svg):
        raise ValueError(f"{source}: expected exactly one <path> and nothing else")
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- GENERATED by app/tools/phosphor2vd.py from {source} (Phosphor Icons, MIT). Do not edit. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp"\n'
        '    android:viewportWidth="256" android:viewportHeight="256">\n'
        f'    <path android:fillColor="#FF000000" android:pathData="{paths[0]}"/>\n'
        "</vector>\n"
    )


def launcher_files(res: str, spec: dict) -> dict:
    """phosphor.json::launcher -> {path under res/: content}: the adaptive foreground in the
    .ai-nav-icon gradient and the one-colour monochrome layer. The colours are copied out of
    colors.xml as literals, because cloud-superapp draws a byte-identical copy and has no such
    colour resources."""
    spec = spec["launcher"]
    name = "ph_" + spec["icon"].replace("-", "_") + ".xml"
    glyph = re.findall(r'android:pathData="([^"]+)"', open(os.path.join(res, "drawable", name), encoding="utf-8").read())
    if len(glyph) != 1:
        raise ValueError(f"drawable/{name}: expected exactly one path")
    colors = dict(re.findall(r'<color name="(\w+)">(#[0-9A-Fa-f]{8})</color>', open(os.path.join(res, "values", "colors.xml"), encoding="utf-8").read()))
    stops = [colors[c] for c in spec["gradient"]]
    size = spec["size_dp"]
    if not 0 < size <= 66:
        raise ValueError("launcher.size_dp must fit the 66dp adaptive safe zone")
    scale = size / 256
    shift = (108 - size) / 2

    def vector(header: str, fill: str) -> str:
        return (
            '<?xml version="1.0" encoding="utf-8"?>\n'
            f"<!-- GENERATED by app/tools/phosphor2vd.py from phosphor.json::launcher (Phosphor {spec['icon']}, MIT): {header}. Do not edit. -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    xmlns:aapt="http://schemas.android.com/aapt"\n'
            '    android:width="108dp" android:height="108dp"\n'
            '    android:viewportWidth="108" android:viewportHeight="108">\n'
            f'    <group android:translateX="{shift:g}" android:translateY="{shift:g}" android:scaleX="{scale:g}" android:scaleY="{scale:g}">\n'
            f"{fill}"
            "    </group>\n"
            "</vector>\n"
        )

    # .ai-nav-icon's linear-gradient(135deg, ...) over the glyph's own 256 box: top-left to bottom-right.
    items = "".join(
        f'                    <item android:offset="{i / (len(stops) - 1):g}" android:color="{c}"/>\n' for i, c in enumerate(stops))
    gradient = (
        f'        <path android:pathData="{glyph[0]}">\n'
        '            <aapt:attr name="android:fillColor">\n'
        '                <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="256" android:endY="256">\n'
        f"{items}"
        "                </gradient>\n"
        "            </aapt:attr>\n"
        "        </path>\n"
    )
    mono = f'        <path android:fillColor="#FF000000" android:pathData="{glyph[0]}"/>\n'
    return {
        "drawable/ic_launcher_foreground.xml": vector("the .ai-nav-icon gradient " + " ".join(spec["gradient"]), gradient),
        "drawable/ic_launcher_monochrome.xml": vector("the themed-icon layer", mono),
    }


def main() -> int:
    spec = json.load(open(os.path.join(HERE, "phosphor.json"), encoding="utf-8"))
    os.makedirs(OUT, exist_ok=True)
    if "--launcher" in sys.argv:
        return write_launcher(spec)
    for weight in ("regular", "fill"):
        for name in spec[weight]:
            file = name if weight == "regular" else f"{name}-fill"
            url = URL.format(version=spec["version"], weight=weight, name=file)
            svg = urllib.request.urlopen(url, timeout=30).read().decode("utf-8")
            res = "ph_" + file.replace("-", "_") + ".xml"
            with open(os.path.join(OUT, res), "w", encoding="utf-8") as f:
                f.write(drawable(svg, f"@phosphor-icons/core@{spec['version']}/assets/{weight}/{file}.svg"))
            print("wrote", res)
    return write_launcher(spec)


def write_launcher(spec: dict) -> int:
    for rel, text in launcher_files(RES, spec).items():
        with open(os.path.join(RES, rel), "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote", rel)
    return 0


if __name__ == "__main__":
    sys.exit(main())
