#!/usr/bin/env python3
"""Phosphor SVG -> Android vector drawable, for the icons app/tools/phosphor.json lists (#797).

Each Phosphor icon is one <path> on a 256x256 viewBox, so the conversion is the path data copied
into a <vector>. The tint comes from Compose (Icon's tint), so the fill colour here is irrelevant.
Run from anywhere: python3 ac_cloud-search/app/tools/phosphor2vd.py
"""
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "main", "res", "drawable")
URL = "https://unpkg.com/@phosphor-icons/core@{version}/assets/{weight}/{name}.svg"


def drawable(svg: str, source: str) -> str:
    if 'viewBox="0 0 256 256"' not in svg:
        raise ValueError(f"{source}: not a 256x256 Phosphor icon")
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if len(paths) != 1 or re.search(r"<(?!/?svg|path)[a-z]", svg):
        raise ValueError(f"{source}: expected exactly one <path> and nothing else")
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- GENERATED by app/tools/phosphor2vd.py from {source} (Phosphor Icons, MIT). Do not edit. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp"\n'
        '    android:viewportWidth="256" android:viewportHeight="256">\n'
        f'    <path android:fillColor="#FF000000" android:pathData="{paths[0]}"/>\n'
        "</vector>\n"
    )


def main() -> int:
    spec = json.load(open(os.path.join(HERE, "phosphor.json"), encoding="utf-8"))
    os.makedirs(OUT, exist_ok=True)
    for weight in ("regular", "fill"):
        for name in spec[weight]:
            file = name if weight == "regular" else f"{name}-fill"
            url = URL.format(version=spec["version"], weight=weight, name=file)
            svg = urllib.request.urlopen(url, timeout=30).read().decode("utf-8")
            res = "ph_" + file.replace("-", "_") + ".xml"
            with open(os.path.join(OUT, res), "w", encoding="utf-8") as f:
                f.write(drawable(svg, f"@phosphor-icons/core@{spec['version']}/assets/{weight}/{file}.svg"))
            print("wrote", res)
    return 0


if __name__ == "__main__":
    sys.exit(main())
