#!/usr/bin/env bash
# Tester (#571): Cloud ▸ Apps ▸ AGI is exactly SuperApp | Terminal | MyTerminal |
# Code | B-LLM | S-LLM, and each launching tile LANDS on the app it is named for.
#
# THE FAILURE THIS EXISTS FOR. #499 pinned the Terminal tile's CAPTION and
# nothing pinned where the tap went: it was app://com.termux.nix with a Play
# Store fallback — the UPSTREAM Nix-on-Droid id, which no fleet build installs —
# so the owner's "Terminal" opened somebody else's store page. MyTerminal named
# the '/files' fork, a separate APK, after #561 made the hub the app. So this
# file resolves every target the way ShellActivity.launchExternalApp does and
# compares the FIRST package it would try with the package the fleet manifest
# (data/constellation-fleet.json, generated by data/regen.sh from each app's own
# build) says that app directory ships. Nothing here names a package id.
#
#   T1  the group's tiles, in order, are the six the owner asked for
#   T2  Terminal/MyTerminal/Code resolve to ac_cloud-nix-on-droid / ac_cloud-myterminal
#       / ac_cloud-code's own package, and install from that app's release_url
#       (#563 follow-up: Terminal moved from ac_cloud-termux to ac_cloud-nix-on-droid)
#   T3  the Code glyph is cloud-code's launcher foreground, byte for byte
#   T4  a not-installed extapp tile draws the #249 placeholder, with strings in
#       every locale, and the install snack is a string resource
#
# Usage: ./test-agi-tiles.sh   (static only, no network, no device)
set -u
APP="$(cd "$(dirname "$0")/.." && pwd)"          # → aa_cloud-superapp
ROOT="$(cd "$APP/.." && pwd)"
for f in "$APP/build.json" "$APP/data/constellation-fleet.json"; do
  [ -f "$f" ] || { echo "ERROR: $f missing — refusing to report a verdict" >&2; exit 2; }
done
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 required" >&2; exit 2; }

python3 - "$APP" "$ROOT" <<'PY'
import json, os, re, sys
app, root = sys.argv[1:3]
passed = failed = 0
def check(cond, msg):
    global passed, failed
    if cond: passed += 1; print("  PASS: " + msg)
    else:    failed += 1; print("  FAIL: " + msg)
def read(p):
    with open(p, encoding="utf-8") as f: return f.read()
def code(p):  # comments stripped, so a doc naming a token cannot satisfy a check
    t = re.sub(r"/\*.*?\*/", "", read(p), flags=re.S)
    return "\n".join(re.sub(r"(?<![:\"])//.*$", "", l) for l in t.splitlines())

bj = json.loads(read(os.path.join(app, "build.json")))
fleet = json.loads(read(os.path.join(app, "data/constellation-fleet.json")))["apps"]
ext = {e["id"]: e for e in bj["ui"]["external_apps"]}

def groups(node):
    if isinstance(node, dict):
        if node.get("title") == "AGI" and isinstance(node.get("tiles"), list): yield node
        for v in node.values(): yield from groups(v)
    elif isinstance(node, list):
        for v in node: yield from groups(v)
agi = list(groups(bj["ui"]["sections"]))
check(len(agi) == 1, "exactly one AGI tile group under ui.sections (found %d)" % len(agi))
if len(agi) != 1: print("-- %d passed, %d failed" % (passed, failed)); sys.exit(1)
tiles = agi[0]["tiles"]

print("== T1: the AGI row is the six tiles the owner asked for, in order ==")
got = [t.get("label") for t in tiles]
want = ["SuperApp", "Terminal", "MyTerminal", "Code", "B-LLM", "S-LLM"]
check(got == want, "AGI captions are %s (want %s)" % (got, want))
by = {t.get("label"): t for t in tiles}

print("== T2: each launching tile resolves to its app's OWN package ==")
def first_candidate(target):
    """ShellActivity.launchExternalApp: fork (if named) → hub → alt; first non-blank."""
    if not target.startswith("extapp:"): return None, None
    appid, _, fork = target[len("extapp:"):].split("#", 1)[0].partition("/")
    e = ext.get(appid)
    if e is None: return None, None
    cands = [(e.get("forks") or {}).get(fork) if fork else None, e.get("hub_package"), e.get("alt_package")]
    return next((c for c in cands if c), None), e
def fleet_for(directory):
    hits = [a for a in fleet if a.get("kind") == "app"
            and a.get("repo_url", "").rstrip("/").endswith("/" + directory)]
    return hits[0] if len(hits) == 1 else None
for label, directory in (("Terminal", "ac_cloud-nix-on-droid"), ("MyTerminal", "ac_cloud-myterminal"),
                         ("Code", "ac_cloud-code")):
    tile, entry = by.get(label), fleet_for(directory)
    check(entry is not None, "fleet manifest has exactly one app built from %s" % directory)
    if tile is None or entry is None: continue
    pkg, e = first_candidate(tile.get("target", ""))
    check(pkg == entry["package"],
          "%s (%s) first launches %r; %s ships %r" % (label, tile.get("target"), pkg, directory, entry["package"]))
    check(e is not None and e.get("install_package") == entry["package"]
          and e.get("install_apk_url") == entry["release_url"],
          "%s installs %s from the fleet's release_url %s" % (label, entry["package"], entry["release_url"]))

print("== T3: the Code glyph is cloud-code's own launcher foreground ==")
ide_icon = (by.get("Code") or {}).get("icon", "")
mine = os.path.join(app, "app/src/main/res/drawable", ide_icon + ".xml")
theirs = os.path.join(root, "ac_cloud-code/res/android/drawable/ic_launcher_foreground.xml")
check(bool(ide_icon) and os.path.isfile(mine) and os.path.isfile(theirs) and read(mine) == read(theirs),
      "drawable/%s.xml is byte-identical to ac_cloud-code's ic_launcher_foreground.xml" % ide_icon)

print("== T4: a not-installed extapp tile is the #249 placeholder, localised ==")
kt = os.path.join(app, "app/src/main/java/com/diegonmarcos/superapp")
grouped = code(os.path.join(kt, "launcher/GroupedTilesFragment.kt"))
cell = grouped[grouped.find("private fun tileCell"):]
cell = cell[:cell.find("\n    private fun ", 1)]
check("Sections.extappMissing(ctx, tile.target)" in cell, "tileCell asks Sections.extappMissing about its target")
for token in ("R.drawable.ic_app_not_installed", "R.string.phone_app_not_installed_tile_hint",
              "R.string.phone_app_not_installed"):
    # \b: phone_app_not_installed is a prefix of phone_app_not_installed_tile_hint,
    # so a plain substring test passed with the "Not installed" caption deleted.
    check(re.search(re.escape(token) + r"\b", cell), "tileCell draws the placeholder with %s" % token)
sections = code(os.path.join(kt, "launcher/Sections.kt"))
fn = sections[sections.find("fun extappMissing"):]
fn = fn[:fn.find("\n    }") + 6]
check("listOfNotNull(fork, app.hubPackage, app.altPackage)" in fn and "getLaunchIntentForPackage" in fn,
      "extappMissing probes the same fork → hub → alt candidates the dispatcher launches")
shell = code(os.path.join(kt, "ShellActivity.kt"))
launch = shell[shell.find("private fun launchExternalApp"):]
launch = launch[:launch.find("\n    }\n") + 6]
check(not re.search(r'snack\("[^"]*not installed', launch),
      "launchExternalApp's install snacks are string resources, not English literals")
for s in ("phone_install_downloading", "phone_install_no_source"):
    check("R.string." + s in launch, "launchExternalApp snacks R.string.%s" % s)
res = os.path.join(app, "app/src/main/res")
locales = sorted(d for d in os.listdir(res) if d.startswith("values") and os.path.isfile(os.path.join(res, d, "strings.xml")))
check("values" in locales and len(locales) > 1, "found the default and at least one translated strings.xml (%s)" % locales)
for d in locales:
    xml = read(os.path.join(res, d, "strings.xml"))
    for s in ("phone_app_not_installed", "phone_app_not_installed_tile_hint",
              "phone_install_downloading", "phone_install_no_source"):
        check('name="%s"' % s in xml, "%s/strings.xml defines %s" % (d, s))

print("-- test-agi-tiles: %d passed, %d failed" % (passed, failed))
sys.exit(1 if failed else 0)
PY
