package com.diegonmarcos.superapp.profile

import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL

/**
 * #778 Drift ▸ UPLOAD L → SERVER: one commit of the local declared file to the vault repo, through
 * GitHub's contents API with the credential Connect holds (gh's token, or a PAT asked for once).
 *
 * WHERE IT LANDS is declared (build.json::ui.profile.drift.upload.path), and it is NOT the server
 * file itself: cloud-vault's profile-secrets.json is GENERATED by its emitter from the sources and
 * guarded against hand edits (emit.py check, run by vault-security-guard on every push), so a
 * phone commit there would turn the vault red and be overwritten by the next emit. The upload is
 * the declared local copy beside it, which emit.py validates and diffs (`check-local`/`local-diff`).
 *
 * Two requests: GET the path for its blob sha (404 = a new file), then PUT the content with that
 * sha, so a file that moved on the server since is refused (409/422) rather than overwritten.
 * The token travels in a header only — never in a URL, never in a result, never logged.
 */
object AccountUpload {

    /** [api] is the contents URL template with `{repo}` and `{path}`; [branch] the ref committed to. */
    data class Target(val api: String, val repo: String, val path: String, val branch: String) {
        val url: String get() = api.replace("{repo}", repo).replace("{path}", path)
    }

    sealed class Result {
        data class Committed(val sha: String, val url: String, val created: Boolean) : Result()
        data class Failed(val status: Int, val reason: String) : Result()
    }

    /** One HTTP exchange: status and body. Tests hand in a mock remote. */
    fun interface Http {
        fun call(method: String, url: String, headers: Map<String, String>, body: String?): Pair<Int, String>
    }

    fun commit(target: Target, token: String, content: ByteArray, message: String, http: Http = UrlHttp): Result {
        if (token.isBlank()) return Result.Failed(0, "no credential")
        val headers = mapOf(
            "Authorization" to "Bearer $token",
            "Accept" to "application/vnd.github+json",
            "X-GitHub-Api-Version" to "2022-11-28",
        )
        val (getStatus, getBody) = runCatching { http.call("GET", target.url + "?ref=" + target.branch, headers, null) }
            .getOrElse { return Result.Failed(0, it.message ?: it.javaClass.simpleName) }
        val sha = when (getStatus) {
            200 -> runCatching { JSONObject(getBody).optString("sha") }.getOrDefault("").ifBlank { null }
            404 -> null
            else -> return Result.Failed(getStatus, reason(getStatus, getBody))
        }
        val put = JSONObject()
            .put("message", message)
            .put("content", java.util.Base64.getEncoder().encodeToString(content))
            .put("branch", target.branch)
        Unit
        val (status, body) = runCatching { http.call("PUT", target.url, headers, put.toString()) }
            .getOrElse { return Result.Failed(0, it.message ?: it.javaClass.simpleName) }
        if (status != 200 && status != 201) return Result.Failed(status, reason(status, body))
        val commit = runCatching { JSONObject(body).optJSONObject("commit") }.getOrNull()
        return Result.Committed(commit?.optString("sha").orEmpty(), commit?.optString("html_url").orEmpty(), created = sha == null)
    }

    /** The server's own message, never the request (which held the token). */
    private fun reason(status: Int, body: String): String {
        val msg = runCatching { JSONObject(body).optString("message") }.getOrDefault("")
        return when (status) {
            401, 403 -> "the credential was refused ($status${if (msg.isBlank()) "" else ": $msg"})"
            409, 422 -> "the file changed on the server since it was read ($status) — fetch again"
            else -> "HTTP $status${if (msg.isBlank()) "" else ": $msg"}"
        }
    }

    /** The phone's [Http]: HttpURLConnection, bounded. Blocking — call on IO. */
    object UrlHttp : Http {
        override fun call(method: String, url: String, headers: Map<String, String>, body: String?): Pair<Int, String> {
            val c = URL(url).openConnection() as HttpURLConnection
            try {
                c.requestMethod = method
                c.connectTimeout = 15_000
                c.readTimeout = 30_000
                headers.forEach { (k, v) -> c.setRequestProperty(k, v) }
                if (body != null) {
                    c.doOutput = true
                    c.setRequestProperty("Content-Type", "application/json")
                    c.outputStream.use { it.write(body.toByteArray()) }
                }
                val status = c.responseCode
                val text = (if (status < 400) c.inputStream else c.errorStream)?.bufferedReader()?.use { it.readText() }.orEmpty()
                return status to text
            } finally {
                c.disconnect()
            }
        }
    }
}
