package com.diegonmarcos.superapp.profile
import com.diegonmarcos.superapp.BuildConfig

import android.content.Context
import android.content.SharedPreferences

/**
 * User profile persistence. Plain SharedPreferences (contact details, not a
 * secret). Defaults seed from `build.json::ui.profile_default` baked into
 * BuildConfig at build time.
 *
 * Consumers:
 *  • Drawer header — shows "{initials} | {mode}", initials DERIVED from [name].
 *  • Configs → Profile page — read/write form bound to these fields.
 *  • [ProfileSync] — mirrors the whole document to the server so the fleet
 *    operator has an out-of-band way to reach people when the update chain
 *    breaks and the app can no longer fix itself.
 *
 * NO CREDENTIALS LIVE HERE. This class is mirrored to the server wholesale by
 * [ProfileSync], so a bearer token or a WireGuard private key added to it
 * would be uploaded. The Authelia bearer lives in
 * `settings.ConfigsPrefs.autheliaToken` (EncryptedSharedPreferences) and the
 * WireGuard private key in `network.WireGuardPrefs.interfacePrivateKey`; the
 * profile screen edits those stores directly and never copies them here.
 *
 * PERSONAL DATA. [name], [email], [phone], [birth] and [location]
 * are personal data under GDPR. Two engineering consequences are load-bearing
 * and must survive future edits:
 *  • [clearPersonalData] exists so an erasure request is one call locally and
 *    one DELETE remotely — never a manual key-by-key sweep that will drift.
 *  • [installId] is a locally generated random UUID, NOT ANDROID_ID / IMEI /
 *    advertising id. Those are device-scoped, shared across apps and cannot be
 *    reset by the user, which turns a contact record into a tracking key.
 *    It is regenerated by [clearPersonalData], so deletion is actually final.
 *
 * MIGRATION — schema v1 dropped the stored `initials` field. Initials are now
 * derived from [name] at render time, so nothing is lost and nothing that used
 * to display them changed. [migrate] removes the orphaned key rather than
 * leaving it on disk: a field we no longer show but still store is one we
 * would have to disclose and delete, for no benefit. Every other key is
 * untouched by the migration, so existing profiles survive intact.
 */
class ProfilePrefs(context: Context) {
    private val sp: SharedPreferences =
        context.getSharedPreferences("profile_prefs", Context.MODE_PRIVATE)

    init { migrate() }

    /**
     * One-shot, forward-only schema migration. Runs on every construction and
     * is a no-op once [K_SCHEMA] reaches [SCHEMA_VERSION].
     *
     * v0 → v1: delete the orphaned `initials` key. Deliberately additive
     * otherwise — the fields added then (phone, birth) need no migration
     * because an absent key already reads as its default, which is exactly the
     * "not filled in yet" state the form shows.
     *
     * v1 → v2: delete `city_from` and `social_links`. Both fields were removed
     * from the form, and personal data that can no longer be viewed or edited
     * but is still on disk (and still uploaded) is the worst of both — so the
     * stored values go with the UI rather than lingering as an undisclosable
     * residue.
     */
    private fun migrate() {
        if (sp.getInt(K_SCHEMA, 0) >= SCHEMA_VERSION) return
        sp.edit()
            .remove("initials")
            .remove("city_from")
            .remove("social_links")
            .putInt(K_SCHEMA, SCHEMA_VERSION)
            .apply()
    }

    var name: String
        get() = sp.getString(K_NAME, BuildConfig.UI_PROFILE_NAME) ?: BuildConfig.UI_PROFILE_NAME
        set(value) { sp.edit().putString(K_NAME, value).apply() }

    var email: String
        get() = sp.getString(K_EMAIL, BuildConfig.UI_PROFILE_EMAIL) ?: BuildConfig.UI_PROFILE_EMAIL
        set(value) { sp.edit().putString(K_EMAIL, value).apply() }

    var phone: String
        get() = sp.getString(K_PHONE, BuildConfig.UI_PROFILE_PHONE) ?: BuildConfig.UI_PROFILE_PHONE
        set(value) { sp.edit().putString(K_PHONE, value).apply() }

    /** ISO-8601 `YYYY-MM-DD`, or empty. Stored as text, not a timestamp: a
     *  birth date is a calendar date with no timezone, and an epoch millis
     *  round-trip shifts it by a day for anyone east or west of the builder. */
    var birth: String
        get() = sp.getString(K_BIRTH, BuildConfig.UI_PROFILE_BIRTH) ?: BuildConfig.UI_PROFILE_BIRTH
        set(value) { sp.edit().putString(K_BIRTH, value).apply() }

    var company: String
        get() = sp.getString(K_COMPANY, BuildConfig.UI_PROFILE_COMPANY) ?: BuildConfig.UI_PROFILE_COMPANY
        set(value) { sp.edit().putString(K_COMPANY, value).apply() }

    var location: String
        get() = sp.getString(K_LOCATION, BuildConfig.UI_PROFILE_LOCATION) ?: BuildConfig.UI_PROFILE_LOCATION
        set(value) { sp.edit().putString(K_LOCATION, value).apply() }

    var website: String
        get() = sp.getString(K_WEBSITE, BuildConfig.UI_PROFILE_WEBSITE) ?: BuildConfig.UI_PROFILE_WEBSITE
        set(value) { sp.edit().putString(K_WEBSITE, value).apply() }

    var titles: String
        get() = sp.getString(K_TITLES, BuildConfig.UI_PROFILE_TITLES) ?: BuildConfig.UI_PROFILE_TITLES
        set(value) { sp.edit().putString(K_TITLES, value).apply() }

    /** Picked from the device gallery via Configs → Profile. Either an
     *  `android.net.Uri` toString() or empty if the user hasn't picked
     *  one yet. BusinessCardFragment falls back to a generated avatar
     *  with initials when this is empty. */
    var pictureUri: String
        get() = sp.getString(K_PICTURE, "") ?: ""
        set(value) { sp.edit().putString(K_PICTURE, value).apply() }

    var bannerUri: String
        get() = sp.getString(K_BANNER, "") ?: ""
        set(value) { sp.edit().putString(K_BANNER, value).apply() }

    /**
     * Stable per-install identifier, generated on first read and kept until
     * the profile is erased.
     *
     * Random UUID on purpose — see the class KDoc. Reconciling the same person
     * across several devices is done SERVER-SIDE by [email], which is the
     * concrete reason email is mandatory rather than merely encouraged: two
     * installs with the same email are one person, and there is no device
     * fingerprint here that could tell you that instead.
     */
    val installId: String
        get() = sp.getString(K_INSTALL_ID, null) ?: java.util.UUID.randomUUID().toString()
            .also { sp.edit().putString(K_INSTALL_ID, it).apply() }

    /**
     * Bearer capability proving this install owns [installId]. Generated
     * locally on first use; the server records it on the first POST and
     * requires it on every later read, write and delete for that id.
     *
     * This is a secret: it must never be logged, shown in the UI, or included
     * in an exported config.
     */
    val installSecret: String
        get() = sp.getString(K_INSTALL_SECRET, null) ?: java.util.UUID.randomUUID().toString()
            .replace("-", "").also { sp.edit().putString(K_INSTALL_SECRET, it).apply() }

    /** Mandatory fields present and plausible. The profile exists to make a
     *  human reachable, so a record without a name and a usable email address
     *  is not a partial profile — it is a useless one. */
    val isComplete: Boolean get() = nameError == null && emailError == null

    /** Human-readable reason [name] is unacceptable, or null when it is fine. */
    val nameError: String? get() = if (name.isBlank()) "Name is required" else null

    /**
     * Same for [email]. The shape check is deliberately loose (something,
     * an @, something, a dot, something): stricter client-side email regexes
     * are famous for rejecting valid addresses, and a false rejection here
     * costs exactly the contact channel this whole feature exists to create.
     */
    val emailError: String? get() = when {
        email.isBlank() -> "Email is required — it is the only way to reach you if an update breaks the app"
        !Regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$").matches(email.trim()) -> "That does not look like an email address"
        else -> null
    }

    /**
     * Avatar initials, DERIVED from [name] — no longer stored (schema v1).
     * First letter of the first and last word, uppercased; "•" when there is
     * no name yet, matching what the avatar used to show for a blank field.
     */
    fun derivedInitials(): String {
        val words = name.trim().split(Regex("\\s+")).filter { it.isNotBlank() }
        return when (words.size) {
            0 -> "•"
            1 -> words[0].take(1).uppercase()
            else -> (words.first().take(1) + words.last().take(1)).uppercase()
        }
    }

    /**
     * Erase every personal field held on this device and cut the link to the
     * server-side record by rotating [installId] / [installSecret].
     *
     * Deliberately a single method rather than the caller clearing keys it
     * happens to remember: the next person to add a field will add it to this
     * class, and a per-key sweep at the call site would silently stop being
     * complete. Non-personal preferences (schema version) survive.
     *
     * Does NOT itself call the server — [ProfileSync.forgetMe] owns ordering
     * (remote DELETE first, then this), because clearing the credential before
     * the DELETE is sent would strand the record on the server forever.
     */
    fun clearPersonalData() {
        sp.edit()
            .remove(K_NAME).remove(K_EMAIL).remove(K_PHONE).remove(K_BIRTH)
            .remove(K_COMPANY).remove(K_LOCATION)
            .remove(K_WEBSITE).remove(K_TITLES)
            .remove(K_PICTURE).remove(K_BANNER)
            .remove(K_INSTALL_ID).remove(K_INSTALL_SECRET)
            .apply()
    }

    companion object {
        /** Bumped when a stored key is removed or its meaning changes. */
        private const val SCHEMA_VERSION = 2

        private const val K_SCHEMA   = "schema_version"
        private const val K_NAME     = "name"
        private const val K_EMAIL    = "email"
        private const val K_PHONE    = "phone"
        private const val K_BIRTH    = "birth"
        private const val K_INSTALL_ID = "install_id"
        private const val K_INSTALL_SECRET = "install_secret"
        private const val K_COMPANY  = "company"
        private const val K_LOCATION = "location"
        private const val K_WEBSITE  = "website"
        // Bumped after the titles default was updated to include emojis
        // — existing installs had the old emoji-less value persisted in
        // the old "titles" key. Renaming the key forces a fresh
        // fall-through to BuildConfig.UI_PROFILE_TITLES.
        private const val K_TITLES   = "titles_v2"
        private const val K_PICTURE  = "picture_uri"
        private const val K_BANNER   = "banner_uri"
    }
}
