"""#802 shared half of the browser testers (imported by test/test-browser-*.sh).

- strip(): comment-stripped Kotlin, string literals preserved (the recipe of
  test-browser-features-wired.sh — a grep cannot tell a call from prose).
- main(check, mutations): run `check` on the real tree, then on a mutated copy per
  mutation; a mutation that leaves the check green is a tester that proves nothing.
- `python3 test/browser_tester.py catalogue` renders docs/settings-catalogue.md.
"""
import json, os, shutil, sys, tempfile

LIB = "ab_cloud-libs-shared/libs/browser/src/main/java/com/diegonmarcos/superapp/browser"
APP = "ac_cloud-browser/app/src/main/java/com/diegonmarcos/cloudbrowser"
MANIFEST = "aa_cloud-superapp/app/src/main/assets/fleet-config.json"
# What a mutated copy needs: the app, the shared browser lib, the fleet manifest.
COPY = ["ac_cloud-browser", "ab_cloud-libs-shared/libs/browser", MANIFEST]
SKIP = shutil.ignore_patterns("build", ".gradle", "dist", ".result")


def strip(src):
    out, i, n, depth = [], 0, len(src), 0
    while i < n:
        two = src[i:i + 2]
        if depth:
            if two == "/*": depth += 1; i += 2; continue
            if two == "*/": depth -= 1; i += 2; continue
            i += 1; continue
        if src[i:i + 3] == '"""':
            j = src.find('"""', i + 3)
            j = n if j < 0 else j + 3
            out.append(src[i:j]); i = j; continue
        if src[i] in ('"', "'"):
            q = src[i]; j = i + 1
            while j < n and src[j] != q:
                j += 2 if src[j] == "\\" else 1
            j = min(j + 1, n)
            out.append(src[i:j]); i = j; continue
        if two == "/*": depth += 1; i += 2; continue
        if two == "//":
            j = src.find("\n", i); i = n if j < 0 else j; continue
        out.append(src[i]); i += 1
    return "".join(out)


def kotlin(root, *dirs):
    """{relpath: stripped source} for every .kt under the given repo-relative dirs."""
    out = {}
    for d in dirs:
        for base, _, files in os.walk(os.path.join(root, d)):
            for f in files:
                if f.endswith(".kt"):
                    p = os.path.join(base, f)
                    out[os.path.relpath(p, root)] = strip(open(p, encoding="utf-8").read())
    return out


def build_json(root):
    return json.load(open(os.path.join(root, "ac_cloud-browser/build.json"), encoding="utf-8"))


def render_catalogue(bj):
    rows = bj["ui"]["browser"].get("settings", [])
    out = ["# Cloud Browser settings catalogue", "",
           "GENERATED by `./build.sh catalogue` from `build.json::ui.browser.settings` — edit the",
           "catalogue, never this file. test-browser-settings-catalogue.sh fails when it is stale.", "",
           "| key | type | default | allowed | section | class | what it does |",
           "|---|---|---|---|---|---|---|"]
    for s in rows:
        if s.get("values_from") == "search_engines":
            allowed = ", ".join(e["id"] for e in bj["ui"]["browser"]["search_engines"])
            default = bj["ui"]["browser"]["default_engine"]
        else:
            allowed = ", ".join(s.get("values", [])) or (
                "%s..%s" % (s["min"], s["max"]) if "min" in s else "")
            default = json.dumps(s.get("default"))
        out.append("| `%s` | %s | %s | %s | %s | %s | %s |" % (
            s["key"], s["type"], default, allowed, s.get("section", ""), s.get("class", ""), s.get("doc", "")))
    return "\n".join(out) + "\n"


def run(check, root):
    fails = []
    def ok(cond, label, detail=""):
        if not cond:
            fails.append(label + ((" — " + detail) if detail else ""))
        return cond
    check(root, ok)
    return fails


def mutated(root, rel, old, new):
    tmp = tempfile.mkdtemp(prefix="browser-mut-")
    for c in COPY:
        src = os.path.join(root, c)
        dst = os.path.join(tmp, c)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        if os.path.isdir(src):
            shutil.copytree(src, dst, ignore=SKIP)
        elif os.path.exists(src):
            shutil.copy2(src, dst)
    p = os.path.join(tmp, rel)
    text = open(p, encoding="utf-8").read() if os.path.exists(p) else ""
    if old is None:
        text = text + new          # append
    else:
        if old not in text:
            shutil.rmtree(tmp)
            return None
        text = text.replace(old, new, 1)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", encoding="utf-8").write(text)
    return tmp


def main(name, check, mutations):
    root = os.environ["ROOT"]
    fails = run(check, root)
    for f in fails:
        print("  FAIL  " + f)
    if fails:
        print("%s: %d assertion(s) failed" % (name, len(fails)))
        sys.exit(1)
    print("  PASS  %s: every assertion holds on the real tree" % name)
    dead = []
    for label, rel, old, new in mutations:
        tmp = mutated(root, rel, old, new)
        if tmp is None:
            dead.append(label + " (mutation target not found — the tester drifted from the code)")
            continue
        try:
            caught = run(check, tmp)
        finally:
            shutil.rmtree(tmp)
        if caught:
            print("  PASS  mutation caught: " + label)
        else:
            dead.append(label)
    if dead:
        for d in dead:
            print("  FAIL  mutation SURVIVED: " + d)
        sys.exit(1)
    print("%s: all assertions passed, %d mutation(s) caught" % (name, len(mutations)))


if __name__ == "__main__" and sys.argv[1:] == ["catalogue"]:
    here = os.path.dirname(os.path.abspath(__file__))
    sys.stdout.write(render_catalogue(build_json(os.path.dirname(os.path.dirname(here)))))
